### ISSUE TITLE
Explicit call to `logging.basicConfig()` in imported module

### ISSUE THREAD

**Issue by andy-slac** [pmelchior/proxmin#15]
`proxmin.algorithms` module calls  `logging.basicConfig()` during import which interferes with normal calls to `basicConfig()` that people usually do at script initialization (https://github.com/pmelchior/proxmin/blob/master/proxmin/algorithms.py#L8). Would it be possible to remove that line completely?

**Comment by pmelchior** [comment]
It should be possible. I'll test it
