### ISSUE TITLE
How to add equality constraints in your algorithm?

### ISSUE THREAD

**Issue by machanic** [pmelchior/proxmin#24]
I have two equality equation constraints in my problem, all of which are quadratic equation.
How to add them in the bSDMM method. I check your example.
Is the argument `prox` for the constraint 
?? (defined in https://github.com/pmelchior/proxmin/blob/master/examples/parabola.py#L30)

How to add my constraints, my objective function are convex function. Can you give me an example?

**Comment by pmelchior** [comment]
You need to formulate the constraints as proximal operators. That's the argument `prox` for the algorithms in this package.

**Comment by machanic** [comment]
@pmelchior I check the README file.
```
def prox_circle(X, step):
    """Projection onto circle"""
    center = np.array([0,0])
    dX = X - center
    # exclude everything other than perimeter of circle
    phi = np.arctan2(dX[1], dX[0])
    return center + radius*np.array([np.cos(phi), np.sin(phi)])
```
Is this the constraint equation? How to set the gradient/derivative formula of the constraint? Which argument? Can you show me an example?

**Comment by machanic** [comment]
Does the formula of the `proximal operators` the same with the constrained formula??

**Comment by machanic** [comment]
Please help me, I am stuck in my research at the constraint problem, I will cite your paper.
I can share you with my objective function and constraint!

**Comment by pmelchior** [comment]
SLSQP would be my first approach here. However, if you want to convert to a proximal formulation, I recommend reading up on proximal operators and algorithms, e.g. in [Parikh & Boyd 2014](https://web.stanford.edu/~boyd/papers/prox_algs.html).
